name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          name: ${{ secrets.SHUTTLE_PROJECT_NAME }}